name: flutter_secure_storage
description: Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
version: 8.0.0
repository: https://github.com/mogol/flutter_secure_storage/tree/develop/flutter_secure_storage

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin
      ios:
        pluginClass: FlutterSecureStoragePlugin
      linux:
        default_package: flutter_secure_storage_linux
      macos:
        default_package: flutter_secure_storage_macos
      web:
        default_package: flutter_secure_storage_web
      windows:
        default_package: flutter_secure_storage_windows

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_linux:
    git:
      url: https://github.com/Eu-Arthur/flutter_secure_storage.git
      path: flutter_secure_storage_linux
  flutter_secure_storage_macos:
    git:
      url: https://github.com/Eu-Arthur/flutter_secure_storage.git
      path: flutter_secure_storage_macos
  flutter_secure_storage_platform_interface:
    git:
      url: https://github.com/Eu-Arthur/flutter_secure_storage.git
      path: flutter_secure_storage_platform_interface
  flutter_secure_storage_web:
    git:
      url: https://github.com/Eu-Arthur/flutter_secure_storage.git
      path: flutter_secure_storage_web
  flutter_secure_storage_windows:
    git:
      url: https://github.com/Eu-Arthur/flutter_secure_storage.git
      path: flutter_secure_storage_windows
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

# We need to manually declare supported platforms, because pub.dev won't find them.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: