name: flutter_secure_storage_web
description: Web implementation of flutter_secure_storage. Use flutter_secure_storage for the full flutter package.
repository: https://github.com/mogol/flutter_secure_storage
version: 1.1.1

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    git:
      url: https://github.com/Eu-Arthur/flutter_secure_storage.git
      path: flutter_secure_storage_platform_interface
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7
  js_wasm:
    git:
      url: https://github.com/Eu-Arthur/JS-WASM.git

dev_dependencies:
  lint: ^1.10.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSecureStorageWeb
        fileName: flutter_secure_storage_web.dart
